import 'package:dartz/dartz.dart';
import '../../core/error/failures.dart';
import '../../domain/entities/service_request_entity.dart';
import '../../infrastructure/models/service_request_model.dart';
import '../../infrastructure/repositories/supabase_service_request_repository.dart';

class ServiceRequestService {
  final SupabaseServiceRequestRepository _repository;

  ServiceRequestService(this._repository);

  Future<Either<Failure, ServiceRequestEntity>> createRequest({
    required String creatorId,
    required List<String> participatingMinerIds,
    required String materialType,
    String? materialCondition,
    int? numberOfSacks,
    required double materialWeight,
    String? source,
    String? notes,
    String? documentUrl,
    required String processingRequirements,
    required String pin,
  }) async {
    // 1. Verify PIN
    final pinValid = await _repository.verifyUserPin(creatorId, pin);
    return pinValid.fold(
      (l) => Left(l),
      (isValid) async {
        if (!isValid) return const Left(ValidationFailure('Incorrect PIN'));

        // 2. Create Request
        final model = ServiceRequestModel(
          id: '', // Generated by DB
          creatorId: creatorId,
          participatingMinerIds: participatingMinerIds,
          materialDetails: MaterialDetails(
            type: materialType,
            condition: materialCondition,
            numberOfSacks: numberOfSacks,
            weight: materialWeight,
            source: source,
            notes: notes,
            documentUrl: documentUrl,
          ),
          processingDetails: ProcessingDetails(
              requirements: processingRequirements, assignedOperatorIds: []),
          status: ServiceRequestStatus.pendingOperatorVerification,
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        );

        final result = await _repository.createServiceRequest(model);
        return result.fold(
          (l) => Left(l),
          (created) async {
            // 3. Log Audit
            await _repository.logAuditTrail(
              requestId: created.id,
              userId: creatorId,
              action: 'CREATE_REQUEST',
              previousStatus: 'None',
              newStatus: ServiceRequestStatus.pendingOperatorVerification.name,
            );
            return Right(created);
          },
        );
      },
    );
  }

  Future<Either<Failure, void>> verifyMaterial({
    required String requestId,
    required String operatorId,
    required double actualWeight,
    required String estimatedTime,
    required bool isAccurate,
    required String pin,
    String? remarks,
    String? corrections,
    required String currentStatus,
  }) async {
    final pinValid = await _repository.verifyUserPin(operatorId, pin);
    return pinValid.fold(
      (l) => Left(l),
      (isValid) async {
        if (!isValid) return const Left(ValidationFailure('Incorrect PIN'));

        final newStatus = isAccurate 
            ? ServiceRequestStatus.verified 
            : ServiceRequestStatus.returnedToMiner;

        final result = await _repository.updateRequestStatus(
          requestId: requestId,
          status: newStatus.name,
          userId: operatorId,
          additionalData: {
            'actual_weight': actualWeight,
            'estimated_time': estimatedTime,
            'verified_by': operatorId,
            'verified_at': DateTime.now().toIso8601String(),
            'is_accurate': isAccurate,
            'verification_remarks': remarks,
            'material_corrections': corrections,
          },
        );

        return result.fold(
          (l) => Left(l),
          (_) async {
            await _repository.logAuditTrail(
              requestId: requestId,
              userId: operatorId,
              action: isAccurate ? 'VERIFY_ACCURATE' : 'VERIFY_INACCURATE',
              previousStatus: currentStatus,
              newStatus: newStatus.name,
              remarks: remarks,
            );
            return const Right(null);
          },
        );
      },
    );
  }

  Future<Either<Failure, void>> minerRespondToReturn({
    required String requestId,
    required String minerId,
    required bool accept,
    required String currentStatus,
  }) async {
    final newStatus = accept ? ServiceRequestStatus.accepted : ServiceRequestStatus.cancelled;
    final result = await _repository.updateRequestStatus(
      requestId: requestId,
      status: newStatus.name,
      userId: minerId,
    );

    return result.fold(
      (l) => Left(l),
      (_) async {
        await _repository.logAuditTrail(
          requestId: requestId,
          userId: minerId,
          action: accept ? 'ACCEPT_CORRECTIONS' : 'CANCEL_REQUEST',
          previousStatus: currentStatus,
          newStatus: newStatus.name,
        );
        return const Right(null);
      },
    );
  }

  Future<Either<Failure, void>> ownerScheduleAndAssign({
    required String requestId,
    required String ownerId,
    required DateTime scheduledDate,
    required List<String> assignedOperatorIds,
    required String currentStatus,
  }) async {
    final result = await _repository.updateRequestStatus(
      requestId: requestId,
      status: ServiceRequestStatus.scheduled.name,
      userId: ownerId,
      additionalData: {
        'scheduled_date': scheduledDate.toIso8601String(),
        'assigned_operators': assignedOperatorIds,
      },
    );

    return result.fold(
      (l) => Left(l),
      (_) async {
        await _repository.logAuditTrail(
          requestId: requestId,
          userId: ownerId,
          action: 'SCHEDULE_AND_ASSIGN',
          previousStatus: currentStatus,
          newStatus: ServiceRequestStatus.scheduled.name,
          remarks: 'Assigned to ${assignedOperatorIds.length} operators',
        );
        return const Right(null);
      },
    );
  }

  Future<Either<Failure, void>> updateProcessingStatus({
    required String requestId,
    required String operatorId,
    required ServiceRequestStatus newStatus,
    required String currentStatus,
    String? remarks,
  }) async {
    final result = await _repository.updateRequestStatus(
      requestId: requestId,
      status: newStatus.name,
      userId: operatorId,
      additionalData: remarks != null ? {'processing_notes': remarks} : null,
    );

    return result.fold(
      (l) => Left(l),
      (_) async {
        await _repository.logAuditTrail(
          requestId: requestId,
          userId: operatorId,
          action: 'UPDATE_PROCESSING',
          previousStatus: currentStatus,
          newStatus: newStatus.name,
          remarks: remarks,
        );
        return const Right(null);
      },
    );
  }

  Future<Either<Failure, void>> completeBilling({
    required String requestId,
    required String ownerId,
    required String billingId,
    required String currentStatus,
  }) async {
    final result = await _repository.updateRequestStatus(
      requestId: requestId,
      status: ServiceRequestStatus.completed.name,
      userId: ownerId,
      additionalData: {'billing_id': billingId},
    );

    return result.fold(
      (l) => Left(l),
      (_) async {
        await _repository.logAuditTrail(
          requestId: requestId,
          userId: ownerId,
          action: 'COMPLETE_BILLING',
          previousStatus: currentStatus,
          newStatus: ServiceRequestStatus.completed.name,
        );
        return const Right(null);
      },
    );
  }
}
