import 'package:dartz/dartz.dart';
import '../../core/error/failures.dart';
import '../../domain/entities/service_request_entity.dart';
import '../../infrastructure/models/service_request_model.dart';
import '../../infrastructure/repositories/supabase_service_request_repository.dart';

class ServiceRequestService {
  final SupabaseServiceRequestRepository _repository;

  ServiceRequestService(this._repository);

  Future<Either<Failure, ServiceRequestEntity>> createRequest({
    required String creatorId,
    required List<String> participatingMinerIds,
    String? materialCondition,
    String? materialState,
    String? materialSourceType,
    int? numberOfSacks,
    String? source,
    String? notes,
    String? documentUrl,
    List<String> photoUrls = const [],
    required String processingRequirements,
    required String pin,
    bool isOperatorAssisted = false,
    String? assistedByOperatorId,
    String? assistedByOperatorName,
    String? estimatedTime, // Only for assisted
  }) async {
    // 1. Verify PIN
    // If operator assisted, the PIN belongs to the primary miner (creatorId)
    final pinValid = await _repository.verifyUserPin(creatorId, pin);
    return pinValid.fold(
      (l) => Left(l),
      (isValid) async {
        if (!isValid) return const Left(ValidationFailure('Incorrect PIN'));

        // 2. Create Request
        final model = ServiceRequestModel(
          id: '', // Generated by DB
          creatorId: creatorId,
          participatingMinerIds: participatingMinerIds,
          materialDetails: MaterialDetails(
            condition: materialCondition,
            state: materialState,
            sourceType: materialSourceType,
            numberOfSacks: numberOfSacks,
            source: source,
            notes: notes,
            documentUrl: documentUrl,
            photoUrls: photoUrls,
          ),
          processingDetails: ProcessingDetails(
            requirements: processingRequirements,
            assignedOperatorIds: [],
            estimatedTime: estimatedTime,
          ),
          status: isOperatorAssisted
              ? ServiceRequestStatus.verified
              : ServiceRequestStatus.pendingOperatorVerification,
          isOperatorAssisted: isOperatorAssisted,
          assistedByOperatorId: assistedByOperatorId,
          approvedBy: isOperatorAssisted ? assistedByOperatorId : null,
          approvedAt: isOperatorAssisted ? DateTime.now() : null,
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        );

        final result = await _repository.createServiceRequest(model);
        return result.fold(
          (l) => Left(l),
          (created) async {
            // 3. MANDATORY: If operator assisted, insert verification record directly into operator_verified_services
            if (isOperatorAssisted && assistedByOperatorId != null) {
              final verificationResult = await _repository.submitOperatorVerification(
                requestId: created.id,
                operatorId: assistedByOperatorId,
                actualSacks: numberOfSacks ?? 0,
                condition: materialCondition ?? 'Rocky',
                state: materialState ?? 'Dry',
                source: source ?? 'N/A',
                isAccurate: true,
                processingEstimate: estimatedTime ?? '3 Hours',
                notes: '${assistedByOperatorName ?? "Operator"} operator assisted request',
              );
              
              // If verification insert fails, we should ideally log it or notify
              verificationResult.fold(
                (l) => print('Warning: Verification record failed to insert: ${l.message}'),
                (_) => print('Success: Verification record inserted directly for assisted request'),
              );
            }

            // 4. Log Audit
            await _repository.logAuditTrail(
              requestId: created.id,
              userId: assistedByOperatorId ?? creatorId,
              action: isOperatorAssisted
                  ? 'OPERATOR_ASSISTED_CREATE'
                  : 'CREATE_REQUEST',
              previousStatus: 'None',
              newStatus: model.status.name,
              remarks: isOperatorAssisted
                  ? 'Created by Operator $assistedByOperatorId on behalf of Miner $creatorId'
                  : null,
            );
            return Right(created);
          },
        );
      },
    );
  }

  Future<Either<Failure, ServiceRequestEntity>> updateRequest({
    required String requestId,
    required String creatorId,
    required List<String> participatingMinerIds,
    String? materialCondition,
    String? materialState,
    String? materialSourceType,
    int? numberOfSacks,
    String? source,
    String? notes,
    List<String> photoUrls = const [],
    required String pin,
  }) async {
    // 1. Verify PIN
    final pinValid = await _repository.verifyUserPin(creatorId, pin);
    return pinValid.fold(
      (l) => Left(l),
      (isValid) async {
        if (!isValid) return const Left(ValidationFailure('Incorrect PIN'));

        // 2. Update Request
        final model = ServiceRequestModel(
          id: requestId,
          creatorId: creatorId,
          participatingMinerIds: participatingMinerIds,
          materialDetails: MaterialDetails(
            condition: materialCondition,
            state: materialState,
            sourceType: materialSourceType,
            numberOfSacks: numberOfSacks,
            source: source,
            notes: notes,
            photoUrls: photoUrls,
          ),
          processingDetails: const ProcessingDetails(
            requirements: '',
            assignedOperatorIds: [],
          ),
          status: ServiceRequestStatus.pendingOperatorVerification, // Reset status to pending
          createdAt: DateTime.now(), // Won't be updated due to repository removal
          updatedAt: DateTime.now(),
        );

        final result = await _repository.updateServiceRequest(model);
        return result.fold(
          (l) => Left(l),
          (updated) async {
            // 3. Log Audit
            await _repository.logAuditTrail(
              requestId: updated.id,
              userId: creatorId,
              action: 'UPDATE_REQUEST',
              previousStatus: 'Unknown',
              newStatus: updated.status.name,
              remarks: 'Request details updated by miner',
            );
            return Right(updated);
          },
        );
      },
    );
  }

  Future<Either<Failure, void>> verifyMaterial({
    required String requestId,
    required String operatorId,
    required int actualSacks,
    required String condition,
    required String state,
    required String source,
    required String estimatedTime,
    required bool isAccurate,
    required String pin,
    String? remarks,
    required String currentStatus,
  }) async {
    final pinValid = await _repository.verifyUserPin(operatorId, pin);
    return pinValid.fold(
      (l) => Left(l),
      (isValid) async {
        if (!isValid) return const Left(ValidationFailure('Incorrect PIN'));

        // Logic Update: When operator submits verification, it always moves to 'verified' 
        // status (In Queue), regardless of whether it was 'accurate' or 'inaccurate' (corrected).
        const newStatus = ServiceRequestStatus.verified;

        // 1. Update the main request status in service_requests table
        final result = await _repository.updateRequestStatus(
          requestId: requestId,
          status: newStatus.name,
          userId: operatorId,
          additionalData: {
            'updated_at': DateTime.now().toIso8601String(),
            'approved_by': operatorId,
            'approved_at': DateTime.now().toIso8601String(),
          },
        );

        return result.fold(
          (l) => Left(l),
          (_) async {
            // 2. Submit the full verification record to the new table
            await _repository.submitOperatorVerification(
              requestId: requestId,
              operatorId: operatorId,
              actualSacks: actualSacks,
              condition: condition,
              state: state,
              source: source,
              isAccurate: isAccurate,
              processingEstimate: estimatedTime,
              notes: remarks,
            );

            // 3. Log Audit Trail
            await _repository.logAuditTrail(
              requestId: requestId,
              userId: operatorId,
              action: isAccurate ? 'VERIFY_ACCURATE' : 'VERIFY_INACCURATE',
              previousStatus: currentStatus,
              newStatus: newStatus.name,
              remarks: remarks,
            );
            return const Right(null);
          },
        );
      },
    );
  }

  Future<Either<Failure, void>> minerRespondToReturn({
    required String requestId,
    required String minerId,
    required bool accept,
    required String currentStatus,
  }) async {
    final newStatus = accept ? ServiceRequestStatus.accepted : ServiceRequestStatus.cancelled;
    final result = await _repository.updateRequestStatus(
      requestId: requestId,
      status: newStatus.name,
      userId: minerId,
    );

    return result.fold(
      (l) => Left(l),
      (_) async {
        await _repository.logAuditTrail(
          requestId: requestId,
          userId: minerId,
          action: accept ? 'ACCEPT_CORRECTIONS' : 'CANCEL_REQUEST',
          previousStatus: currentStatus,
          newStatus: newStatus.name,
        );
        return const Right(null);
      },
    );
  }

  Future<Either<Failure, void>> addToGeneralQueue({
    required String requestId,
    required String userId,
    required String currentStatus,
  }) async {
    // Looking at the schema constraint: CHECK (status::text = ANY (ARRAY['draft'::text, 'pending'::text, 'pendingOperatorVerification'::text, 'returnedToMiner'::text, 'accepted'::text, 'verified'::text, 'scheduled'::text, 'assigned'::text, 'processing'::text, 'processingCompleted'::text, 'goldHandoff'::text, 'completed'::text, 'cancelled'::text]))
    // The word 'queued' does NOT exist in the check constraint ARRAY for the database table!
    // Therefore, we must use 'verified' or 'accepted' or 'scheduled' for the table status.
    // Let's use 'verified' as the status which represents it's verified and ready in the queue, or 'scheduled' for a specific timeframe.
    final statusResult = await _repository.updateRequestStatus(
      requestId: requestId,
      status: ServiceRequestStatus.verified.name,
      userId: userId,
    );

    return statusResult.fold(
      (l) => Left(l),
      (_) async {
        final queueResult = await _repository.addToMillQueue(
          requestId: requestId,
          userId: userId,
          queueType: 'general',
        );

        return queueResult.fold(
          (l) => Left(l),
          (_) async {
            await _repository.logAuditTrail(
              requestId: requestId,
              userId: userId,
              action: 'ADD_TO_QUEUE',
              previousStatus: currentStatus,
              newStatus: ServiceRequestStatus.verified.name,
              remarks: 'Moved to general mill queue by admin',
            );
            return const Right(null);
          },
        );
      },
    );
  }

  Future<Either<Failure, void>> ownerScheduleAndAssign({
    required String requestId,
    required String ownerId,
    required DateTime scheduledDate,
    required List<String> assignedOperatorIds,
    required String currentStatus,
  }) async {
    // The previous implementation tried to pass 'assigned_operators' or 'scheduled_date'
    // directly into additionalData for updateRequestStatus, which doesn't exist on the table.
    // Looking at schema.sql for service_requests table: it has 'approved_at', 'approved_by', and status columns.
    final result = await _repository.updateRequestStatus(
      requestId: requestId,
      status: ServiceRequestStatus.scheduled.name,
      userId: ownerId,
      additionalData: {
        'approved_by': ownerId,
        'approved_at': scheduledDate.toIso8601String(),
      },
    );

    return result.fold(
      (l) => Left(l),
      (_) async {
        // Also insert into mill_queue table with queue_type 'scheduled'
        final queueResult = await _repository.addToMillQueue(
          requestId: requestId,
          userId: ownerId,
          queueType: 'scheduled',
          scheduledAt: scheduledDate,
        );

        return queueResult.fold(
          (l) => Left(l),
          (_) async {
            await _repository.logAuditTrail(
              requestId: requestId,
              userId: ownerId,
              action: 'SCHEDULE_AND_ASSIGN',
              previousStatus: currentStatus,
              newStatus: ServiceRequestStatus.scheduled.name,
              remarks: 'Assigned to ${assignedOperatorIds.length} operators and added to mill queue',
            );
            return const Right(null);
          },
        );
      },
    );
  }

  Future<Either<Failure, void>> updateProcessingStatus({
    required String requestId,
    required String operatorId,
    required ServiceRequestStatus newStatus,
    required String currentStatus,
    ProcessingStage? newStage,
    int? sackedQuantity,
    String? remarks,
  }) async {
    final result = await _repository.updateRequestStatus(
      requestId: requestId,
      status: newStatus.name,
      userId: operatorId,
      additionalData: {
        if (remarks != null) 'processing_notes': remarks,
        if (newStage != null) 'current_processing_stage': newStage.name,
        if (sackedQuantity != null) 'sacked_quantity': sackedQuantity,
      },
    );

    return result.fold(
      (l) => Left(l),
      (_) async {
        // Automatically update the matching mill_queue table item if processing starts or completes
        if (newStatus == ServiceRequestStatus.processing) {
          try {
            await _repository.updateMillQueueStatus(requestId: requestId, status: 'in_progress');
          } catch (_) {}
        } else if (newStatus == ServiceRequestStatus.processingCompleted) {
          try {
            await _repository.updateMillQueueStatus(requestId: requestId, status: 'completed');
          } catch (_) {}
        }

        await _repository.logAuditTrail(
          requestId: requestId,
          userId: operatorId,
          action: 'UPDATE_PROCESSING',
          previousStatus: currentStatus,
          newStatus: newStatus.name,
          remarks: newStage != null ? 'Moved to stage: ${newStage.name}' : remarks,
        );
        return const Right(null);
      },
    );
  }

  Future<Either<Failure, void>> claimAndStartService({
    required String requestId,
    required String operatorId,
    required String currentStatus,
  }) async {
    // 1. Mark as processing in main table
    final statusResult = await _repository.updateRequestStatus(
      requestId: requestId,
      status: ServiceRequestStatus.processing.name,
      userId: operatorId,
      additionalData: {'current_processing_stage': ProcessingStage.rebagging.name},
    );

    return statusResult.fold(
      (l) => Left(l),
      (_) async {
        // 2. Insert into ongoing_services
        final ongoingResult = await _repository.claimServiceRequest(
          requestId: requestId,
          operatorId: operatorId,
        );

        return ongoingResult.fold(
          (l) => Left(l),
          (_) async {
            // 3. Update mill_queue to in_progress
            await _repository.updateMillQueueStatus(requestId: requestId, status: 'in_progress');

            // 4. Log Audit
            await _repository.logAuditTrail(
              requestId: requestId,
              userId: operatorId,
              action: 'CLAIM_SERVICE',
              previousStatus: currentStatus,
              newStatus: ServiceRequestStatus.processing.name,
              remarks: 'Service claimed and started by operator',
            );
            return const Right(null);
          },
        );
      },
    );
  }

  Future<Either<Failure, void>> completeBilling({
    required String requestId,
    required String ownerId,
    required String billingId,
    required String currentStatus,
  }) async {
    final result = await _repository.updateRequestStatus(
      requestId: requestId,
      status: ServiceRequestStatus.completed.name,
      userId: ownerId,
      additionalData: {'billing_id': billingId},
    );

    return result.fold(
      (l) => Left(l),
      (_) async {
        await _repository.logAuditTrail(
          requestId: requestId,
          userId: ownerId,
          action: 'COMPLETE_BILLING',
          previousStatus: currentStatus,
          newStatus: ServiceRequestStatus.completed.name,
        );
        return const Right(null);
      },
    );
  }
}
